name: test-build-audit-actions
on: [push]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install and test
        run: |
          npm install
          npm test
        env:
          CI: true
      - name: build package
        run: npm run build
      - name: audit dependencies
        run: npm run audit
  deploy:
    needs: [sanity]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "animated-parakeet"
          heroku_email: "ngzhaoloong@gmail.com"
