name: test-build-audit-actions
on: [push, pull_request]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
      - name: install and test
        run: npm test
        env:
          CI: true
      - name: build package
        run: npm run build
      - name: audit dependencies
        run: npm run audit
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [sanity]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "animated-parakeet"
          heroku_email: "ngzhaoloong@gmail.com"
  smoke:
    if: github.ref == 'refs/heads/master'
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: cypress-io/github-action@v2
        with:
          headless: true
          browser: chrome
          quiet: true
